version: "3"
services:
  app:
    build:
      context: .
      dockerfile: scanning_bee/Dockerfile.app
    container_name: scanning_bee_app
    ports:
      - "8000:8000"
    volumes:
      - ./scanning_bee:/scanning_bee
    depends_on:
      - db
    environment:
      - DEBUG=1

  db:
    build:
      context: .
      dockerfile: Database/Dockerfile.db
    container_name: scanning_bee_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=scanning_bee_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
